name: Build Samsung Galaxy A71 (Based AOSP & OneUI A16)

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-kernel:
    name: ${{ matrix.ksu.name }} for Galaxy A71
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false # Đặt false để nếu 1 bản build lỗi, bản kia vẫn tiếp tục chạy
      matrix:
        ksu:
          - name: "ReSukiSU"
            fork: "resukisu"
            suffix: "ReSukiSU"
          - name: "KernelSU Next"
            fork: "next"
            suffix: "KernelSU-Next"

    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"

      # Device env
      DEVICE_NAME : "samsung_a71"
      DEVICE_CODENAME : "a71"

      CUSTOM_CMDS : "CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu-"
      EXTRA_CMDS : "LLVM=1 LLVM_IAS=1 CC=clang LD=ld.lld AR=llvm-ar NM=llvm-nm OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump STRIP=llvm-strip READELF=llvm-readelf HOSTCC=clang HOSTCXX=clang++"

      KERNEL_SOURCE : "https://github.com/nduykha/kernel_samsung_sm7150.git"
      KERNEL_BRANCH : "paradigm"

      CLANG_SOURCE : "https://github.com/nduykha/kernel_samsung_sm7150/releases/download/clang/llvm.tar.xz"
      CLANG_BRANCH : ""

      GCC_GNU : true
      GCC_64_SOURCE : "https://github.com/nduykha/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu.git"
      GCC_64_BRANCH : "main"
      GCC_32_SOURCE : ""
      GCC_32_BRANCH : ""

      DEFCONFIG_SOURCE: ""
      DEFCONFIG_NAME : "sdmmagpie_defconfig"
      DEFCONFIG_ORIGIN_IMAGE: ""
      DEFCONFIG_FROM_BOOT: false

      KERNELSU_SOURCE : ""
      KERNELSU_BRANCH : ""

      KERNELSU_AUTO_GET : "true"
      # Gọi giá trị fork từ matrix
      KERNELSU_AUTO_FORK : "${{ matrix.ksu.fork }}"

      SUSFS_ENABLE : true
      SUSFS_FIXED : true

      AK3_SOURCE : "https://github.com/osm0sis/AnyKernel3.git"
      AK3_BRANCH : "master"

      BOOT_SOURCE : ""

      NEED_DTBO : true
      NEED_SAFE_DTBO : true

      ROM_TEXT : "aosp_oneui_a16"

      # Other env
      PYTHON_VERSION: "3"
      PACK_METHOD: "Anykernel3"
      PACK_KMODULES: "false"

      KERNELSU_METHOD: "shell"

      PATCHES_SOURCE: "JackA1ltman/NonGKI_Kernel_Patches"
      PATCHES_BRANCH: "samsung_kernel"

      SUSFS_FOLDER_FIXED: "a71_sm7150"
      SUSFS_PATCH_FIXED: "susfs_fixed"

      REKERNEL_ENABLE: "true"
      DROIDSPACES_ENABLE: "false"

      HOOK_METHOD: "syscall"

      KERNEL_PATCH: "true"

      KPM_ENABLE: "true"
      KPM_INLINE: "false"
      KPM_KPATCH_NEXT: "false"
      KPM_PATCH_SOURCE: "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU_patch/refs/heads/main/kpm/patch_linux"

      BASEBAND_GUARD_ENABLE: "true"
      BASEBAND_GUARD_BOOT: "false"

      GENERATE_DTB: "false"
      GENERATE_CHIP: "qcom"

      BUILD_DEBUGGER: "false"
      SKIP_PATCH: "false"

      BUILD_OTHER_CONFIG: "true"
      MERGE_CONFIG_FILES: "a71.config"

      FREE_MORE_SPACE: "false"

    steps:
      - name: ⏰ Checkout repository
        uses: actions/checkout@v4 # Đổi thành v4 vì v6 chưa tồn tại, Github Actions có thể báo lỗi

      - name: ⌛️ Compilation environment preparation
        uses: ./.github/workflows/build-env

      - name: ⚙️ Get neccssary tools
        uses: ./.github/workflows/build-ready

      - name: 🪝 Patch Kernel of SUSFS
        uses: ./.github/workflows/patch-susfs

      - name: 🔗 Patch for no-kprobe
        uses: ./.github/workflows/patch-no-kprobe

      - name: 🪛 Extra Kernel Options
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          sed -i 's/CONFIG_LOCALVERSION="-Paradigm"/CONFIG_LOCALVERSION="-HaoticKernel"/g' arch/arm64/configs/sdmmagpie_defconfig

          # Gọi tên suffix từ matrix
          echo "[+] Kernel name has been updated to -HaoticKernel-${{ matrix.ksu.suffix }}"

          sed -i -e '/CONFIG_DEBUG_KERNEL/d' -e '/CONFIG_KALLSYMS/d' -e '/CONFIG_KALLSYMS_ALL/d' arch/arm64/configs/sdmmagpie_defconfig
          cat <<EOF >> arch/arm64/configs/sdmmagpie_defconfig
          CONFIG_DEBUG_KERNEL=y
          CONFIG_KALLSYMS=y
          CONFIG_KALLSYMS_ALL=y
          EOF
          echo "[+] Fixed KPM feature"

      - name: 🧰 Patch Kernel of Re:Kernel
        uses: ./.github/workflows/patch-rekernel

      - name: 💿 Patch Kernel of Droidspaces
        uses: ./.github/workflows/patch-droidspaces

      - name: 🔒 Patch Kernel of Baseband Guard
        uses: ./.github/workflows/patch-baseband-guard

      - name: 🚀 Build Process
        uses: ./.github/workflows/build-process

      - name: 🔍 Verify and Create DTBO Image
        run: |
          cd $GITHUB_WORKSPACE/device_kernel
          echo "🔍 Searching for .dtbo files..."
          DTBO_FILES=$(find out/arch/arm64/boot/dts/samsung/ -name "sm*150-sec-a71-eur-overlay-*.dtbo")

          if [ -z "$DTBO_FILES" ]; then
            echo "❌ No .dtbo files found! Check your build log for dtbs errors."
            exit 1
          fi

          echo "📦 Creating dtbo.img..."
          ./tools/mkdtimg create out/arch/arm64/boot/dtbo.img --page_size=4096 ${DTBO_FILES}

          if [ -f "out/arch/arm64/boot/dtbo.img" ]; then
            echo "✅ DTBO created successfully at out/arch/arm64/boot/dtbo.img"
          else
            echo "❌ DTBO creation failed! Listing files for debug:"
            find out/ -name "*.img"
            exit 1
          fi

      - name: 🔩 Pack Process
        uses: ./.github/workflows/pack-process

      - name: ✏️ Upload Artifacts
        uses: ./.github/workflows/upload-files
